name: dispatch-event-test
on:
  workflow_dispatch:
    inputs:
      name:
        required: false
        default: "test"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world! '${{ github.event.inputs.name }}'
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
